sudo: false

language: java

jdk:
- oraclejdk8

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - $HOME/.m2

install: true

before_script:
- export TZ=Europe/Berlin

script: mvn --settings maven-settings.xml clean verify

deploy:
  provider: releases
  api_key:
    secure: V8OjmrVF0fszRYoyydItRZMALU8B5NsQZt9d90XXqU+7ywprPmMrcoRDlBXtPF+opKesWl7f3E67xUcz3rsXlYNLPrYct7YkXssgC0logIYIMuVezSW4RyJNoIO7OkTbcVXKwhE89poSK3XAzk3V72OKbbF+zea/aH2Yjyrn6zhGpJu6wkvzMV7RwEHho3BQEeyks1Terj2rMX55MmH/+wiQNiz2FPn/UL+R3zAk+0d84Tq/gfBz6JiSuRStxbjftmyfrPAvfBp2ektPN392YbuG7hKGc4IADaUilG5n/iTfcr9z6KeUswtMd5xTZyspj/UggP9hhycusjrBtIwO0IRM0elJRATLyBfEsKiTBfaNohJxb0qIImha+elo70s/TocTLyzdym75f+q7vf8K2P9AOAeby6oJwykcKC3Smpyn6CL+A+z/mAez51fZ1226v+S0cXOFViqiZDuOCoTuENYwaoHxQcHj36k33j8dLNuF+L+P6ent14gaiCYrXCL5cCJQOkqfwW7Rd3Pu6/Wf4ZJZ3e7FIVT20UiboTmPwAY76JKssz2PSJEGjABO6qPo9/4R4mWG1XtXwFuEBnYMRACg1be7PHDKjKCzKUlHpCL168GWRIt1Aq6bdwTYhon4yfHT1HVTvk4c05mmkUMBF2e+SBjd9cAOyYjXXM3k6p0=
  file: "./target/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/locationstore
